source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '17.5'

target 'Example' do
  use_frameworks!
  pod 'MQTTClient', '0.15.3'
end

target 'UITests' do
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "17.5"
    end
  end
end

